sudo: required
services:
  - docker

jobs:
  include:
    - stage: PHP 7.3
      env:
        - TMP_IMAGE_NAME=nginx-phpfpm:7.3
      script:
        - docker build -t $TMP_IMAGE_NAME -f php73.dockerfile .
        - sh tests/install_tools.sh
        - ./container-structure-test test --image $TMP_IMAGE_NAME --config tests/image_tests.yaml
        - ./container-structure-test test --image $TMP_IMAGE_NAME --config tests/nginx_tests.yaml
        - ./container-structure-test test --image $TMP_IMAGE_NAME --config tests/php_tests.yaml
        - ./container-structure-test test --image $TMP_IMAGE_NAME --config tests/supervisord_tests.yaml
    - stage: PHP 7.2
      env:
        - TMP_IMAGE_NAME=nginx-phpfpm:7.2
      script:
        - docker build -t $TMP_IMAGE_NAME -f php72.dockerfile .
        - sh tests/install_tools.sh
        - ./container-structure-test test --image $TMP_IMAGE_NAME --config tests/image_tests.yaml
        - ./container-structure-test test --image $TMP_IMAGE_NAME --config tests/nginx_tests.yaml
        - ./container-structure-test test --image $TMP_IMAGE_NAME --config tests/php_tests.yaml
        - ./container-structure-test test --image $TMP_IMAGE_NAME --config tests/supervisord_tests.yaml
    - stage: PHP 7.1
      env:
        - TMP_IMAGE_NAME=nginx-phpfpm:7.1
      script:
        - docker build -t $TMP_IMAGE_NAME -f php71.dockerfile .
        - sh tests/install_tools.sh
        - ./container-structure-test test --image $TMP_IMAGE_NAME --config tests/image_tests.yaml
        - ./container-structure-test test --image $TMP_IMAGE_NAME --config tests/nginx_tests.yaml
        - ./container-structure-test test --image $TMP_IMAGE_NAME --config tests/php_tests.yaml
        - ./container-structure-test test --image $TMP_IMAGE_NAME --config tests/supervisord_tests.yaml
