sudo: required
services:
  - docker

jobs:
  include:
    - stage: PHP 7.3
      script:
        - docker build -t nginx-phpfpm:7.3 -f php73.dockerfile .
        - sh tests/install_tools.sh
        - ./container-structure-test test --image nginx-phpfpm:7.3 --config tests/nginx_tests.yaml
        - ./container-structure-test test --image nginx-phpfpm:7.3 --config tests/php_tests.yaml
        - ./container-structure-test test --image nginx-phpfpm:7.3 --config tests/supervisord_tests.yaml
    - stage: PHP 7.2
      script:
        - docker build -t nginx-phpfpm:7.2 -f php72.dockerfile .
        - docker run -d --name nginx-phpfpm-72 -p 8000:80 -v "$(pwd)/www:/app/public" nginx-phpfpm:7.2
        - docker stop nginx-phpfpm-72
